from PIL import Image, ImageDraw, ImageFont
import textwrap
from pathlib import Path
from typing import Optional

def generate_health_card(
    risk_level: str,
    details: str,
    language: str = "en",
    output_path: Path = Path("health_card.png")
) -> Path:
    """
    Generates a visual health report card.
    risk_level: 'low', 'medium', 'high'
    """
    
    # Color Scheme
    colors = {
        "low": ("#4CAF50", "#E8F5E9"),     # Green
        "medium": ("#FFC107", "#FFF8E1"),  # Amber
        "high": ("#F44336", "#FFEBEE")     # Red
    }
    
    base_color, bg_color = colors.get(risk_level.lower(), ("#9E9E9E", "#F5F5F5"))
    
    # Canvas
    width, height = 800, 1000
    img = Image.new('RGB', (width, height), color='white')
    draw = ImageDraw.Draw(img)
    
    # Header Background
    draw.rectangle([(0, 0), (width, 200)], fill=base_color)
    
    # Text Setup (Using default font because we don't have custom fonts installed safely)
    # real app should use a .ttf font
    try:
        font_header = ImageFont.truetype("arial.ttf", 60)
        font_body = ImageFont.truetype("arial.ttf", 40)
        font_small = ImageFont.truetype("arial.ttf", 30)
    except IOError:
        font_header = ImageFont.load_default()
        font_body = ImageFont.load_default()
        font_small = ImageFont.load_default()

    # Title
    title_text = "Health Screening Report"
    if language == "hi":
        title_text = "स्वास्थ्य जांच रिपोर्ट" # This might not render well without a unicode font
        
    draw.text((50, 70), title_text, fill="white", font=font_header)
    
    # Risk Box
    draw.rectangle([(50, 250), (750, 450)], fill=bg_color, outline=base_color, width=3)
    
    risk_display = f"Risk Level: {risk_level.upper()}"
    draw.text((100, 320), risk_display, fill=base_color, font=font_header)
    
    # Recommendations
    rec_text = "Recommendations:\n" + details
    wrapped_text = textwrap.fill(rec_text, width=40)
    
    draw.text((50, 500), wrapped_text, fill="black", font=font_body)
    
    # Footer
    footer = "Generated by AI Health Assistant. Consult a doctor for diagnosis."
    draw.text((50, 900), footer, fill="gray", font=font_small)
    
    img.save(output_path)
    return output_path
